###########################################################
# GCC template makefile
###########################################################

MANGO_Z1_USB_HD_SOURCES = 
MANGO_Z1_USB_HD_SOURCES += 



EXTRAINCDIRS += $(TOP)/SampleChapter/StudyCode/MStory2.0/MANGO-Z1/09.Z1.Src009.USB.HID/Inc


C_SOURCES += $(MANGO_Z1_USB_HD_SOURCES)